### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by jimmyn** [MONEI/MONEI-WooCommerce#50]
We need to display a human-readable error message to the client on the checkout page

<img width="1128" alt="image" src="https://github.com/MONEI/MONEI-WooCommerce/assets/5391775/9f91a6ba-8546-4301-bc70-ba8fcc05c844">

Subtasks

1. Display human-readable error (the error message only) if there is an error that comes from the client. To reproduce this error insert a name with special characters in the Woo checkout form.
2. Hook into the validation form process in Woo and add our own validation rule. [WooCommerce_after_checkout_validation](https://woocommerce.github.io/code-reference/files/woocommerce-includes-class-wc-checkout.html#source-view.961) Throw a human-readable translatable error if the validation does not pass. "Please enter a valid name. Special characters are not allowed."

**Comment by greguly** [comment]
Are there any instructions to reproduce it?
