### ISSUE TITLE
Card input error message

### ISSUE THREAD

**Issue by jimmyn** [MONEI/MONEI-WooCommerce#56]
Whenever a customer clicks on the "Place Order" button and the card is invalid, such as a missing CVC code, the following error message is displayed:

<img width="355" alt="image" src="https://github.com/user-attachments/assets/eabe59d1-2435-4c2b-9295-a6d645b7a9b2">

Check how `CardInput` is implemented in the demo - https://github.com/MONEI/monei-payments-demo/blob/master/public/javascript/payment.js#L162-L227

### Release Candidate
5.8.13

**Comment by greguly** [comment]
Ready for a review :)
