### ISSUE TITLE
installation instructions in readme are wrong

### ISSUE THREAD

**Issue by alexandresaiz** [MONEI/MONEI-WooCommerce#8]
we are stating:
== Installation ==

In order to use this plugin you need to be registered in [MONEI](https://monei.net/)

* go to [MONEI Dashboard](https://dashboard.monei.net/)
* select your sub account
* go to *Ecommerce Guides -> WooCommerce* and follow the instructions there

@joseconti is this the flow a normal user would follow?

**Comment by joseconti** [comment]
Maybe the correct workflow is:

== Installation ==

* Go to wp-admin > Plugins
* Click Add new
* Search for MONEI
* Press Install
* Press Activate now
* Go to WooCommerce > Settings > Payments > MONEI
* Add your Account ID & Password.

If you don't have you Account ID & Password

* go to MONEI Dashboard
* select your sub account
* go to Ecommerce Guides -> WooCommerce and follow the instructions there

**Comment by alexandresaiz** [comment]
@joseconti update it and when live, ping so we can go over there and when "touching" your new approach apply the fixes if needed. thanks!

**Comment by joseconti** [comment]
@alexandresaiz done

https://wordpress.org/plugins/monei/#installation

**Comment by alexandresaiz** [comment]
@joseconti thanks!
small things here: 
typo: YOU (should be YOUR)

AND.
this is not right:
Select your sub account
Go to Ecommerce Guides -> WooCommerce and follow the instructions there

do you need a demo account?

**Comment by joseconti** [comment]
@alexandresaiz  Yes, it would be a good idea to have a demo account. That way I would be able to see the whole process (especially in case someone asks me).

What is wrong with:

Select your sub account
Go to Ecommerce Guides -> WooCommerce and follow the instructions there

I just delete it?

**Comment by alexandresaiz** [comment]
@joseconti sign up for a https://www.monei.net/ account do the onboarding (add white pdfs) as requested documents and we'll validate your account internally so you have full access to the whole platform.

**Comment by alexandresaiz** [comment]
@joseconti once you have the account you'll be able to "write" or update the installation instructions.

**Comment by joseconti** [comment]
Ok @alexandresaiz Done.

Thank you
